### ISSUE TITLE
Create members database

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#2]
In the `members` app add the following tables to `models.py`. Django documentation [here](https://docs.djangoproject.com/en/3.2/topics/db/models/).

![image](https://user-images.githubusercontent.com/43474282/140618381-dd6b29c6-d287-4aea-a7d5-3217aaa83038.png)

Field constraints (docs [here](https://docs.djangoproject.com/en/3.2/ref/models/fields/)):
- `UUID` is primary key 
- `username` and `email` should be marked as unique
- `username`, `password`, `active` and `email` should be marked as not null
- `username` is foreign key in both tables
- also note the max length in case of varchar attributes
- use on_delete: cascade

NOTE: The passwords will be hashed, NOT stored in plain text!
Edit: Add a [UUIDField](https://www.geeksforgeeks.org/uuidfield-django-models/) to the users table

**Comment by StefanoSperetta** [comment]
Looks good to me. Usually, you could store the password hash seed in a configuration file so that a default seed can be visible on the GitHub page but the application will use a customized (hardened) set of settings.

One comment on the first_name and last_name fields: I would rather not store/ask them as these are info that can be used to identify a person (basically falling under GDPR). Not that the username cannot be used to identify a person, but this is up to the user to select and might be a "random" name.

I would also add one extra boolean field "Active" defaulting to true such that we could eventually block users. Not that I have the intention now, but just in case.

**Comment by NotUnlikeTheWaves** [comment]
Is there a reason to have the passwords stored in a separate table?

**Comment by StefanoSperetta** [comment]
One comment about user login: if we use the users also as radio amateurs, we will need to store the password in plain text on the radio amateur machine (I guess I will have to do something similar for the application connecting the radio on the computer at EWI to the server) since we will probably use an automated application.

In this case, it might be easier to add yet another field o the user setting containing a random UID (like a 20 characters random string) that could be used to submit the frames and connect to the server (but not for login in on the portal). This would basically create 2 domains, one (the website) accessible via password (where you could also change the password and the UID) and the data submission with only the UID (and no possibility to change it). This would provide a more secure system as a leak of the UID would not lead to a password leak.

**Comment by iiacoban42** [comment]
Good point! Updated the issue. Should we also do sessions, auto logout after x amount of inactivity?
