### ISSUE TITLE
Getting started with Grafana

### ISSUE THREAD

**Issue by iiacoban42** [iiacoban42/DelfiTLM#76]
This article sounds like a good starting point: https://www.sipios.com/blog-tech/monitoring

- Setup Grafana for our app
- Define the input data for the dashboard

We need to discuss this one a bit, like what we'll plot and where/how we'll get the data.

**Comment by StefanoSperetta** [comment]
I read a bit about grafana integration in external websites and about private dashboards (requiring authentication, I think it will be very useful to be able to display private dashboards). The simplest way seems to have an LDAP server using Django, as in [here](https://xael.org/using-django-as-an-ldap-server-en.html) to provide authentication).

This can also allow authenticating pgadmin using a Django user instead of hardcoding usernames.

**Comment by iiacoban42** [comment]
Sounds nice! I'll read up on it too, I'm a Grafana newbie currently.
